In [ ]:
#Numpy-A package in python

#numpy library is used to perform mathematical operations on numpy arrays.
#

In [2]:
#numpy array is n dimensional container of data like integers and strings.
#It is similar to lists

In [ ]:
# arr1=[.p.array(1,2,3,4,5,10)]
# # 

In [1]:
import numpy as np
import pandas as pd

In [5]:
# df=pd.read_csv(r'E:\DS projects(only ipynb files & datasets)\A Study On Agriculture Commodities Price Prediction and Forecasting\Agriculture_commodities_dataset.csv')
# df               

In [4]:
arr1=np.array([1,2,3])
#1 dimensional array..array of integers

In [6]:
type(arr1)

numpy.ndarray

In [7]:
arr1

array([1, 2, 3])

In [12]:
arr1/2

array([0.5, 1. , 1.5])

In [10]:
l1=[1,3,5]

In [11]:
l1/2

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [13]:
op=[]
for i in l1:
    op.append(i/2)
print(op)

[0.5, 1.5, 2.5]


In [ ]:
#mylist=[[1,2,3],[1,1,1]]

In [17]:
arr2=np.array([[1,2,3,8],[3,4,5,77],[1,1,1,1],..,[sublist number 100]])
#.ndim
#dimension of array.no: of rows is 2
#[1,2,3] - 1 d list
#[[1,2,3],[3,3,3]]-2 d list

In [18]:
arr2.ndim
#list of lists is 2d array
#

2

In [ ]:
mylist=[1,2,3]

In [4]:
np.array([["cha",True,4+9j],[2,3,4],[5,6,7],[2,3,4]]).ndim

2

In [24]:
np.arange(start=5,stop=13,step=4)
#5 to n-1 with a step of 4

array([5, 9])

In [39]:
arr2=np.random.randint(6,17,size=(3,2))
#size=2

In [46]:
arr2

array([[15,  9],
       [12, 14],
       [10, 11]])

In [ ]:
#reshapes the array to have 3 columns 
#with the no. of rows to be automatically determined based on 
#the total no. of elements in the original array

In [42]:
arr2.reshape(-1,3)
#(r,c)

array([[15,  9, 12],
       [14, 10, 11]])

In [45]:
arr2.reshape(1,-1)

array([[15,  9, 12, 14, 10, 11]])

In [ ]:
# np.random.choice()

In [ ]:
#above codes generates integer below code generates array of integers

In [15]:
np.random.randint(1,21,(3,3))
#generates random integers in a given range in 3*3 format

array([[ 2, 17, 11],
       [15,  5, 18],
       [19,  8,  2]])

In [7]:
np.random.randint(1,21,(2,3))

array([[18, 15, 12],
       [10,  1, 13]])

In [ ]:
#np.array()-converts a 1d/2d lists into array variable.
#arange-it gives me  a range of array numbers

In [48]:
a=np.arange(2,21,+3)
a
#it can take value upto 20

array([ 2,  5,  8, 11, 14, 17, 20])

In [52]:
a=np.arange(22,8,-8)
a

#we get a range of numbers from start to stop minus 1 with a c.d of 3
#it can take value upto 7

array([22, 14])

In [22]:
# for i in range(21,3,-1):
#     print(i)
#takes a value upto 4 when we come in descending order here.

In [57]:
arr1=np.linspace(1,10,num=15,endpoint=True,retstep=True)
arr1

(array([ 1.        ,  1.64285714,  2.28571429,  2.92857143,  3.57142857,
         4.21428571,  4.85714286,  5.5       ,  6.14285714,  6.78571429,
         7.42857143,  8.07142857,  8.71428571,  9.35714286, 10.        ]),
 0.6428571428571429)

In [62]:
arr1=np.linspace(1,2,num=50,endpoint=False,retstep=True)
arr1
#access  2 from 2. of array of numbers from linspace fun.

#Return evenly spaced numbers over a specified interval.

#linspace fun gives us 10 numbers from 1 to 20 with a common difference.

(array([1.  , 1.02, 1.04, 1.06, 1.08, 1.1 , 1.12, 1.14, 1.16, 1.18, 1.2 ,
        1.22, 1.24, 1.26, 1.28, 1.3 , 1.32, 1.34, 1.36, 1.38, 1.4 , 1.42,
        1.44, 1.46, 1.48, 1.5 , 1.52, 1.54, 1.56, 1.58, 1.6 , 1.62, 1.64,
        1.66, 1.68, 1.7 , 1.72, 1.74, 1.76, 1.78, 1.8 , 1.82, 1.84, 1.86,
        1.88, 1.9 , 1.92, 1.94, 1.96, 1.98]),
 0.02)

In [ ]:
# for i in arr1:
#     print(int(i))
# a[i][0] 
# #str.slice(0,1)

In [ ]:
#A few attributes of the numpy array:Attributes describe an array object.
⚬ size
⚬ shape
⚬ ndim
⚬ dtype
#functions  have parenthesis.Attributes do not have parenthesis.





In [2]:


#array var.size gies number of elements in the array.
#arange fun gives an array of numbers

In [1]:
# arr1=np.array(([1,2,3],["cha","True",True]))
# arr1


In [33]:
#slicing in 2 d array
# arr1[1,-3:-2]

#var[r,c]

#slices the elements in row index 1 and col index 0 to 1


In [51]:
#indexing-access an element in an array
#slicing-access group of elements in an array

In [35]:
arr2=np.array([5,2,41])
arr2

array([ 5,  2, 41])

In [20]:
arr2[arr2<10]
#array[if condn]
#we get array of int which satisfy the condition

array([5, 2])

In [21]:
arr2<10

array([ True,  True, False])

In [22]:
arr2

array([ 5,  2, 41])

In [36]:
arr2*4
#array multiplication
# 4 is multiplied with all array numbers

array([ 20,   8, 164])

In [ ]:
#2 d list is a list of lists.

In [39]:
#Multiply numbers in 2 d list
list2d = [[1,2,3],[3,4,5],[6,7,1]]
print(list2d)
arr2d=np.array(list2d)#array function converts 2 d list to 2 d array
print(arr2d)
print("----")
print(arr2d*5)

[[1, 2, 3], [3, 4, 5], [6, 7, 1]]
[[1 2 3]
 [3 4 5]
 [6 7 1]]
----
[[ 5 10 15]
 [15 20 25]
 [30 35  5]]


In [9]:
#l1.append(exp value) means  expression value gets appened into the list one by one.l1 will not be empty.
#l1.append([expression value]) means list is appended into a list.2d list.

#print([[j*5 for j in i] for i in a])

In [10]:
list2d

NameError: name 'list2d' is not defined

In [42]:
list2d
#Multiply elements of a 2 d list

[[1, 2, 3], [3, 4, 5], [6, 7, 1]]

In [41]:
l1 = []
for i in list2d:
#     print(i)
    
    l1.append([j*5 for j in i])
print(l1)
#every time the lc expression value is put into the lc variable inside append fun.
#once lc is complete,append fun appends the value into list l1.
#[[5,10,15],[15,20,25],[,,]]
# [[],[],[]]

#[[5,10,15],[15,20,25],[30,35,5]]
###

[[5, 10, 15], [15, 20, 25], [30, 35, 5]]


In [64]:
print([[j*5 for j in i] for i in list2d])
#[[],[],[]]

[[5, 10, 15], [15, 20, 25], [30, 35, 5]]


In [9]:
mylist=[]
l1=mylist.append([i*2 for i in range(4)])
# #[0,2,4,9]
mylist

[[0, 2, 4, 6]]

In [19]:
arr1

NameError: name 'arr1' is not defined

In [ ]:
#np.arange(),np.linspace(),
#array()-converts a 1dlist/2dlist to 1d/2d array.

In [10]:
mylist

[[0, 2, 4, 6]]

In [2]:
import numpy as np

In [6]:
#np.sqrt([4,9])

In [8]:
#Transpose of a matrix


In [1]:
import numpy as np

In [ ]:
# np.square() 

In [45]:
M = [[25, 14, 42, 52], [74, 22, 45, 93], [84, 33, 23, 31], [23, 37, 14, 20]]
M=np.array([[25, 14, 42, 52], [74, 22, 45, 93], [84, 33, 23, 31], [23, 37, 14, 20]])
print("M: ",M)
print("Transpose of M ")
print(np.transpose(M))
#transpose of a matrix means all columns become corresponding rows
#col at index 0 becomdes row at index 0

M:  [[25 14 42 52]
 [74 22 45 93]
 [84 33 23 31]
 [23 37 14 20]]
Transpose of M 
[[25 74 84 23]
 [14 22 33 37]
 [42 45 23 14]
 [52 93 31 20]]


In [ ]:
#Login api
#get 2 values emailid 
#cj@gmail.com
#id=101,name:chandru,age:20,email:cj@gmail.com,pass:1234
#sign in successfully when pass validation is true
#invalid password.



In [45]:
username=input("enter username")
password=input("enter password")
value =False
print("check the database")
j=['sam','james','jack']
dic={index:value for index,value in enumerate(j)}
print(dic)
#1 st iter,access index and value of 'sam'
#2 nd iter,index and value takes 2 and james
#to get the values printed along with their index I can use Python's enumerate function 
us_pass_dict={'same':'12345','james':'22222','jack':'pas'}
#i create a dict of usernames and passwords as key value paairs.
#length of usernames is 5.we have 5 usernames in our list.
for i in range(0,len(j)):#i takes i=0,1,2,
    if username not in dic.get(i):
        

enter usernamech
enter passwordas
check the database
{0: 'sam', 1: 'james', 2: 'jack'}


In [ ]:
#(ord(y)>=97 and ord(y)<=122) means characters in lowers

In [8]:
#Calculate bmi of 7 patients.
#19 to 25,
#<19 underweight 25>ioverweight,obese patient.

22.49134948096886

In [2]:
import numpy as np

In [ ]:
#Calculate BMI of 7 students using array concept.

In [44]:
weights = np.array([67, 68, 58, 60 ,79, 92, 46])
heights =np.array([1.89, 1.05, 1.98, 1.78, 1.65, 1.43, 1.23])

BMI=weights/(heights**2)
print("BMI",BMI)
#can be executed by map and lambda fun in lists
#w is array of numbers
#h is array of numbers
#mathe expression is applied on all adjacent elements of arrays
#op number is appended into the op array.(bmi)

BMI [18.75647378 61.67800454 14.79440873 18.9370029  29.0174472  44.98997506
 30.4051821 ]


In [46]:
w=[67, 68, 58, 60 ,79]
h=[1.89, 1.05, 1.98, 1.78,2.01]
BMI=[]
for i in range(0,len(w)):
    exp_val=w[i]/(h[i]**2)
    BMI.append(exp_val)
print(BMI)
#1 st iter,
#     for j in range(0,len(h)):
#         if i==j:
#             exp_val=w[i]/(h[i]**2)
#             BMI.append(exp_val)
# print(BMI)

[18.75647378292881, 61.67800453514739, 14.794408733802674, 18.93700290367378, 19.55397143635059]


In [1]:
w=[67, 68, 58, 60 ,79]
h=[1.89, 1.05, 1.98, 1.78,2.01]
BMI=[]
for i in range(0,len(w)):
    for j in range(0,len(h)):
        if i==j:
            exp_val=w[i]/(h[i]**2)
            BMI.append(exp_val)
print(BMI)
#bmi=[18,61,14,]          
#when the inner for loop is finished,ctrl moves to outer for loop.
#inner loop will run all the times from begining one by one




#ad of numpy array over lists:less memory,less time,less code,faster,
    

[18.75647378292881, 61.67800453514739, 14.794408733802674, 18.93700290367378, 19.55397143635059]


In [4]:
import numpy as np

In [49]:
w=[67, 68, 58, 60 ,79]
h=[1.89, 1.05, 1.98, 1.78,2.01]
np.array(list(map(lambda w,h:w/(h**2),w,h)))

array([18.75647378, 61.67800454, 14.79440873, 18.9370029 , 19.55397144])

In [17]:
#np.ceil(4.1),np.floor(2.9)


In [14]:
num = [64,56, 32,16]
# num_arr=np.array(num)
# num_arr%12
#the above methematical operation,condition is applied on all numers in the array one by one.the op value is
#displayed in array.

In [ ]:
#Advantage of arrays:mathe matic expressions are applied on all elements of the array.eg:arr1%7

In [17]:
list(map(lambda x:x/7,num))
#no need to pass map,lambda fun in arrays.

[9.142857142857142, 8.0, 4.571428571428571, 2.2857142857142856]

In [16]:
56/7

8.0

In [2]:
import numpy as np

In [4]:
#I am concatenating(joining) both arrays along row wise.
a=np.array([[1,2,3],[2,2,2]])
b=np.array([[3,3,3],[3,3,3]])
print(a)
print(b)
np.concatenate((a,b),axis=1)
#concatenated along a new row. join a sequence of arrays along an existing axis

[[1 2 3]
 [2 2 2]]
[[3 3 3]
 [3 3 3]]


array([[1, 2, 3, 3, 3, 3],
       [2, 2, 2, 3, 3, 3]])

In [8]:
np.concatenate((a,b),axis=1)

array([[1, 2, 3, 3, 3, 3],
       [2, 2, 2, 3, 3, 3]])

In [ ]:
#Q) Perform (5x**2)/(x-1) on every element of an array.
#Here,x is number of array

In [7]:
range(1,11)

range(1, 11)

In [27]:
#(np.arange(1,10)
#`range` function, but returns an ndarray rather than a list.


In [1]:
import numpy as np

In [5]:
np.arange(1,19)
#

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])

In [7]:
np.ceil(4.0001),np.floor(4.000000006)
#2 sep funs...

(5.0, 4.0)

In [13]:
np.floor(4.9)#nearest lowest whole number

4.0

In [24]:
arr1=np.array(range(1,11))
arr1
np.array(list(map(lambda x:(5*x**2)/(x+1),arr1)))
#range object which has numbers 1 to 10.range object is converted to array var by np.array()

array([ 2.5       ,  6.66666667, 11.25      , 16.        , 20.83333333,
       25.71428571, 30.625     , 35.55555556, 40.5       , 45.45454545])

Numpy vs Pandas

In [ ]:
#NumPy module works with numerical data.
#Functions of numpy are array(),arange(),linspace(),square(),Transpose()
#Numpy lib consumes less memory
#(imp)multi dimensional array(nd array) stores data

#Pandas module works with the tabular data.
#Functions of pandas library are Series(),DataFrame(),merge()
#Pandas lib consumes more memory
#(imp)Dataframes store data in rows and columns.

In [64]:
import numpy as np
import pandas as pd
import seaborn as sns

In [66]:
df=sns.load_dataset('iris')
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [71]:
df.species.value_counts()

versicolor    50
setosa        50
virginica     50
Name: species, dtype: int64

In [77]:
df.loc[df.species=='setosa']['sepal_width'].min()

2.3

In [ ]:
#When we set *args and **kwargs in fun definition parameter it means that we pass tuple and dict data.

In [ ]:
#TypeError: my_func() takes 1 positional argument but 5 were given means when i set args instead of *
#when weset fun defition as *args it means that i tell the udf that u r going to receive a tuple
#when i set args it means that fun will think args as a variable.how can a variable receive a tuple data.it is wrong.
#so we ust set* args


In [4]:
import numpy as np

In [6]:
# *args is used to pass number of arguments
def my_func(*a):
    print(a)
    return np.square(a)
my_func(1,2,3,4,5)


(1, 2, 3, 4, 5)


array([ 1,  4,  9, 16, 25])

In [11]:
def my_func(*args):
    return np.mean(args)
my_func(1,2,3,4,5)

3.0

In [11]:
# **kwargs 
def my_func(**a):
#     print(kwargs)
    print("hi")
    b1=a
    kwargs=b1
    return (a)
my_func(num1=10,n2=6,c1=30,j9=8)

hi


{'num1': 10, 'n2': 6, 'c1': 30, 'j9': 8}

In [17]:
# **kwargs 
def my_func(**kwargs):
    print(kwargs)
    return (kwargs)
my_func(num1=10,num2=85,n3=7)
#1 st dict data is displayed due to print stmt
# 2nd dict data is displayed due to return keyword

{'num1': 10, 'num2': 85, 'n3': 7}


{'num1': 10, 'num2': 85, 'n3': 7}

In [23]:
#A tuple is passed into the fun and summ of all the integers are displayed.
def adder(*num): 
    summ = 0 
    for n in num:
        summ-= n 
    print("Sum:",summ)
    return summ+1
print(adder(3,8))
print(adder(4,5,4,7))
print(adder(1,2,3,5,6))#we can write a udf without return stmt too.

Sum: -11
-10
Sum: -20
-19
Sum: -17
-16


In [26]:
# **kwargs 
def my_func(**kwargs):
    total=0
    print(kwargs)
    for i in kwargs.values():
#         print(i)
        total+=i
    return total
my_func(n=12,n1=12,n2=20,n3=10)
#return "hi" will return the "hi" string to function call.
#mathematical calculations will be stored in var named total

{'n': 12, 'n1': 12, 'n2': 20, 'n3': 10}


54

In [30]:
def my_func(**kwargs):
    total=0
#     print(kwargs)
    for i in kwargs.items():
        print(i)
#         print(i[0])
        total+=i[1]
    return total
my_func(k1=12,k2=10,k3=20,k4=0)

('k1', 12)
('k2', 10)
('k3', 20)
('k4', 0)


42

In [ ]:
#c11@gmail.com"
#'1'

In [ ]:
# def category(bmi):
#     if bmi<18.5:
#         return "underweight"
#     elif 18.5<=bmi<+24.9:
#         return "fit"
#     else:
#         return "overweight"
# df['category']=df['bmi'].apply(category)
# df
# avgexpenditure_cat_wise=pd.pivot_table(df,index=['category'],values=['expenditure'],aggfunc=np.average)
# avgexpenditure_cat_wise
#

In [15]:
#np.ceil(3.1)
# np.floor(3.9)

3.0

In [16]:
#merge() allows you to perform inner join, left outer join,right outer join and full outer join in pandas.
#inner join-matching rows of both df(common rows of common cols)
#right outer join:joins right df rows+matching rows
#left outer join:joins left df rows+matching rows
#outer join:joins all rows of both df


In [1]:
import pandas as pd#difference btw pandas and numpy...r

In [ ]:
#Data Frames has data in table format.It has records in columns and rows.

In [32]:
pd.DataFrame()
#converts lists,arrays,dictionaries into dataframe

Empty DataFrame
Columns: []
Index: []

In [9]:
df1 = pd.DataFrame({ 
   'Emp_ID': [1001,1002,1003,1004,1005],
    
   'Name': ['Chan', 'Catherine', 'Lilly', 
            'BRandon', 'Steve'],
   'Gender':['M', 'F', 'F', 'M', 'M'],
   'Company':['Apple','Walmart','Intel','SHiash','Ford'],
   'Salary':[67000,90000,87000,69000,78000]})
df1
#employee details
#index=["a","b","c","d","e"]

Emp_ID       Name Gender  Company  Salary
0    1001       Chan      M    Apple   67000
1    1002  Catherine      F  Walmart   90000
2    1003      Lilly      F    Intel   87000
3    1004    BRandon      M   SHiash   69000
4    1005      Steve      M     Ford   78000

In [10]:
#convert dict to df
#convert 2dlist to df

df3=pd.DataFrame({'Emp_ID':[1004,1005,1006],'Number_of_dependents':[2,3,2],'Savings':[30000,35000,20000]})

df3#personal details

Emp_ID  Number_of_dependents  Savings
0    1004                     2    30000
1    1005                     3    35000
2    1006                     2    20000

In [ ]:
#index=["a","b","c","d","e"]

In [6]:
pd.merge(df3,df1,how='inner',on='Emp_ID')

Emp_ID  Number_of_dependents  Savings     Name Gender Company  Salary
0    1004                     2    30000  BRandon      M  SHiash   69000
1    1005                     3    35000    Steve      M    Ford   78000

In [8]:
pd.merge(df1,df3,how='inner',on='Emp_ID')

Emp_ID     Name Gender Company  Salary  Number_of_dependents  Savings
0    1004  BRandon      M  SHiash   69000                     2    30000
1    1005    Steve      M    Ford   78000                     3    35000

In [12]:
df1

Emp_ID       Name Gender  Company  Salary
0    1001       Chan      M    Apple   67000
1    1002  Catherine      F  Walmart   90000
2    1003      Lilly      F    Intel   87000
3    1004    BRandon      M   SHiash   69000
4    1005      Steve      M     Ford   78000

In [13]:
df3

Emp_ID  Number_of_dependents  Savings
0    1004                     2    30000
1    1005                     3    35000
2    1006                     2    20000

In [11]:
pd.merge(df1,df3,how='right',on='Emp_ID')

Emp_ID     Name Gender Company   Salary  Number_of_dependents  Savings
0    1004  BRandon      M  SHiash  69000.0                     2    30000
1    1005    Steve      M    Ford  78000.0                     3    35000
2    1006      NaN    NaN     NaN      NaN                     2    20000

In [14]:
pd.merge(df3,df1,how='right',on='Emp_ID')

Emp_ID  Number_of_dependents  Savings       Name Gender  Company  Salary
0    1001                   NaN      NaN       Chan      M    Apple   67000
1    1002                   NaN      NaN  Catherine      F  Walmart   90000
2    1003                   NaN      NaN      Lilly      F    Intel   87000
3    1004                   2.0  30000.0    BRandon      M   SHiash   69000
4    1005                   3.0  35000.0      Steve      M     Ford   78000

In [17]:
pd.merge(df1,df3,how='left',on='Emp_ID')

Emp_ID       Name Gender  Company  Salary  Number_of_dependents  Savings
0    1001       Chan      M    Apple   67000                   NaN      NaN
1    1002  Catherine      F  Walmart   90000                   NaN      NaN
2    1003      Lilly      F    Intel   87000                   NaN      NaN
3    1004    BRandon      M   SHiash   69000                   2.0  30000.0
4    1005      Steve      M     Ford   78000                   3.0  35000.0

In [16]:
pd.merge(df3,df1,how='left',on='Emp_ID')

Emp_ID  Number_of_dependents  Savings     Name Gender Company   Salary
0    1004                     2    30000  BRandon      M  SHiash  69000.0
1    1005                     3    35000    Steve      M    Ford  78000.0
2    1006                     2    20000      NaN    NaN     NaN      NaN

In [18]:
pd.merge(df1,df3,how='outer',on='Emp_ID')
#the on parameter must have a columnn in both the dataframes

Emp_ID       Name Gender  Company   Salary  Number_of_dependents  Savings
0    1001       Chan      M    Apple  67000.0                   NaN      NaN
1    1002  Catherine      F  Walmart  90000.0                   NaN      NaN
2    1003      Lilly      F    Intel  87000.0                   NaN      NaN
3    1004    BRandon      M   SHiash  69000.0                   2.0  30000.0
4    1005      Steve      M     Ford  78000.0                   3.0  35000.0
5    1006        NaN    NaN      NaN      NaN                   2.0  20000.0

In [19]:
pd.merge(df3,df1,how='outer',on='Emp_ID')

Emp_ID  Number_of_dependents  Savings       Name Gender  Company   Salary
0    1004                   2.0  30000.0    BRandon      M   SHiash  69000.0
1    1005                   3.0  35000.0      Steve      M     Ford  78000.0
2    1006                   2.0  20000.0        NaN    NaN      NaN      NaN
3    1001                   NaN      NaN       Chan      M    Apple  67000.0
4    1002                   NaN      NaN  Catherine      F  Walmart  90000.0
5    1003                   NaN      NaN      Lilly      F    Intel  87000.0

In [6]:
df2 = pd.DataFrame({
    'Emp_ID': [1004,1005,1006,1007,1008,1009],
   'Name': ['Andy', 'ALice', 'Will', 'Joy', 'kristen','vani'],
    'Gender':['M', 'M', 'M', 'M', 'F','F'],
   'Company':['Cognizant','Apple','Intel','Cummins','Walmart','Intel'],
   'Salary':[89000,80000,79000,97000,88000,89000]},
   index=[106,107,108,109,110,111])
df2

Emp_ID     Name Gender    Company  Salary
106    1004     Andy      M  Cognizant   89000
107    1005    ALice      M      Apple   80000
108    1006     Will      M      Intel   79000
109    1007      Joy      M    Cummins   97000
110    1008  kristen      F    Walmart   88000
111    1009     vani      F      Intel   89000

In [22]:
pd.merge(df1,df2,how='inner',on='Emp_ID')
#merge function performs an inneer join on both the dataframes.
#matching elements of common columns of both df are selected or displayed.

Emp_ID   Name_x Gender_x Company_x  Salary_x Name_y Gender_y  Company_y  \
0    1004  BRandon        M    SHiash     69000   Andy        M  Cognizant   
1    1005    Steve        M      Ford     78000  ALice        M      Apple   

   Salary_y  
0     89000  
1     80000

In [ ]:
#suffix x represents df 1's features.
#create df with empid,num of dependents,savings per month,own a house or not3

In [4]:
pd.merge(df1,df2,how='right',on='Emp_ID')

Emp_ID   Name_x Gender_x Company_x  Salary_x   Name_y Gender_y  Company_y  \
0    1004  BRandon        M    SHiash   69000.0     Andy        M  Cognizant   
1    1005    Steve        M      Ford   78000.0    ALice        M      Apple   
2    1006      NaN      NaN       NaN       NaN     Will        M      Intel   
3    1007      NaN      NaN       NaN       NaN      Joy        M    Cummins   
4    1008      NaN      NaN       NaN       NaN  kristen        F    Walmart   
5    1009      NaN      NaN       NaN       NaN     vani        F      Intel   

   Salary_y  
0     89000  
1     80000  
2     79000  
3     97000  
4     88000  
5     89000

In [7]:
pd.merge(df2,df1,how='left',on='Emp_ID')
#merge function performs left outer join.all rows of left col+matching rows of both df are merged.

Emp_ID   Name_x Gender_x  Company_x  Salary_x   Name_y Gender_y Company_y  \
0    1004     Andy        M  Cognizant     89000  BRandon        M    SHiash   
1    1005    ALice        M      Apple     80000    Steve        M      Ford   
2    1006     Will        M      Intel     79000      NaN      NaN       NaN   
3    1007      Joy        M    Cummins     97000      NaN      NaN       NaN   
4    1008  kristen        F    Walmart     88000      NaN      NaN       NaN   
5    1009     vani        F      Intel     89000      NaN      NaN       NaN   

   Salary_y  
0   69000.0  
1   78000.0  
2       NaN  
3       NaN  
4       NaN  
5       NaN

In [8]:
pd.merge(df1,df2,how='outer',on='Emp_ID')

Emp_ID     Name_x Gender_x Company_x  Salary_x   Name_y Gender_y  \
0    1001       Chan        M     Apple   67000.0      NaN      NaN   
1    1002  Catherine        F   Walmart   90000.0      NaN      NaN   
2    1003      Lilly        F     Intel   87000.0      NaN      NaN   
3    1004    BRandon        M    SHiash   69000.0     Andy        M   
4    1005      Steve        M      Ford   78000.0    ALice        M   
5    1006        NaN      NaN       NaN       NaN     Will        M   
6    1007        NaN      NaN       NaN       NaN      Joy        M   
7    1008        NaN      NaN       NaN       NaN  kristen        F   
8    1009        NaN      NaN       NaN       NaN     vani        F   

   Company_y  Salary_y  
0        NaN       NaN  
1        NaN       NaN  
2        NaN       NaN  
3  Cognizant   89000.0  
4      Apple   80000.0  
5      Intel   79000.0  
6    Cummins   97000.0  
7    Walmart   88000.0  
8      Intel   89000.0

In [ ]:
#concatenate and merge funtion

#replace elements rows and columns ina  df(note important....)

In [1]:
#LINEAR relationship btw t.v and input features.
#No LINEAR relationship btw/amongst indep features.

In [ ]:
#pandas,series and df

In [ ]:
#convert a 2 d array into a matrix.We cannot convert 1 d array into a matrix.

In [10]:
a=pd.DataFrame({'store':("a","b","c"),'sales':(100,200,305)})
a

store  sales
0     a    100
1     b    200
2     c    305

In [ ]:
#df=pd.read_csv("")
#

In [1]:
import pandas as pd

1)Select the rows from below dataframe where marks are less than 50.

Name    Marks
Jay     90
Raju    32
Ishan   89
Nithya  55


In [ ]:
Df[] is a function in df.it is used to retrieve data from df based on a condition.

In [ ]:
#convert data to df

#df[where conditon ]- select records which satisfy the condition
#df[(where condn 1)&(where condn 2)]-Select records/rows which satisfy both codns.

In [2]:
df=pd.DataFrame({'Name':['Jay','Raju','Ishan','Nithya'],'Marks':[90,32,89,55]})
df

Name  Marks
0     Jay     90
1    Raju     32
2   Ishan     89
3  Nithya     55

In [3]:
df[df['Marks']<50]
#
#Select records "where marks is less than 50"

Name  Marks
1  Raju     32

In [ ]:
#df[df['Marks']<50].iloc[[0],[0]]


In [ ]:
#2)Select  jay's marks

In [4]:
df[df['Name']=='Jay']
#Select rows "where name is equal to jay"
#df[condn]

Name  Marks
0  Jay     90

In [5]:
df[df['Name']!='Jay']#Select records where name is not Jay

Name  Marks
1    Raju     32
2   Ishan     89
3  Nithya     55

In [12]:
df[df['Marks']==89]

Name  Marks
2  Ishan     89

In [7]:
#display the students name who scored 55 marks.
a=df[df['Marks']==55]
# type(a)
# type(a.Name[3])
# # type(a)
# #type(a['Name'][3])
# a['Name']
a

Name  Marks
3  Nithya     55

In [ ]:
#Series means values of a column only.no column name here.
#column consists of col name and values.

#Sales of different companies in different cities

In [ ]:
Retail_shops   City     Sales
Croma          Chennai  60000
Reliance_mart  Kovai    50000
RMKV           Tirupati 70000
Chennai_silks  Hyd      55000
Big_basket     Tirupati 40000
Walmart        Chennai  30000
Reliance_mart  Hyd      55000
RMKV           Hyd      40000
Chennai_silks  Kovai    30000
Big_basket     Agra     70000
Walmart        Pune     40000
Big_basket     Agra     50000
Walmart        Chennai  55000


In [1]:

import pandas as pd

In [3]:
df=pd.DataFrame({'Retail_shops':('Croma','Reliance_mart','RMKV','Chennai_silks','Big_basket',
                              'Walmart','Reliance_mart','RMKV','Chennai_silks','Big_basket',
                             'Walmart','Big_basket','Walmart'),
                 "City":("Chennai","Kovai","Tirupati","Hyd","Tirupati",
                          "Chennai","Hyd","Hyd","Kovai","Agra","Pune","Agra","Chennai"),
             "Sales":(60000,50000,70000,55000,40000,30000,55000,40000,30000,70000,40000,50000,55000)})
df

Retail_shops      City  Sales
0           Croma   Chennai  60000
1   Reliance_mart     Kovai  50000
2            RMKV  Tirupati  70000
3   Chennai_silks       Hyd  55000
4      Big_basket  Tirupati  40000
5         Walmart   Chennai  30000
6   Reliance_mart       Hyd  55000
7            RMKV       Hyd  40000
8   Chennai_silks     Kovai  30000
9      Big_basket      Agra  70000
10        Walmart      Pune  40000
11     Big_basket      Agra  50000
12        Walmart   Chennai  55000

In [ ]:
#a df which has details of companies,departments,employees their assets and salary
#exp col error-Lengths must be same in all columns
#column length of city is 12 whereas col length of 2 cols are 13 because i have not specified comma.


In [ ]:
#df['col'] = df['col'].map({'A':'Store_A','B':'Store_B','C':'Store_C','D':'Store_D'})

In [11]:
# df.City=df.City.map({'Chennai':"c",na_action='ignore'})
#map fun renames values of a series only not for a dataframe..

In [15]:
df

Retail_shops      City  Sales
0           Croma   Chennai  60000
1   Reliance_mart     Kovai  50000
2            RMKV  Tirupati  70000
3   Chennai_silks       Hyd  55000
4      Big_basket  Tirupati  40000
5         Walmart   Chennai  30000
6   Reliance_mart       Hyd  55000
7            RMKV       Hyd  40000
8   Chennai_silks     Kovai  30000
9      Big_basket      Agra  70000
10        Walmart      Pune  40000
11     Big_basket      Agra  50000
12        Walmart   Chennai  55000

1)Write a program to select the rows where the sales are higher than 40000 in Chennai.

In [ ]:
#city,sales

In [13]:

df
#df[((df['City']=='Chennai')&(df['Sales']>40000))]

Retail_shops      City  Sales
0           Croma   Chennai  60000
1   Reliance_mart     Kovai  50000
2            RMKV  Tirupati  70000
3   Chennai_silks       Hyd  55000
4      Big_basket  Tirupati  40000
5         Walmart   Chennai  30000
6   Reliance_mart       Hyd  55000
7            RMKV       Hyd  40000
8   Chennai_silks     Kovai  30000
9      Big_basket      Agra  70000
10        Walmart      Pune  40000
11     Big_basket      Agra  50000
12        Walmart   Chennai  55000

In [10]:
df[((df['City']=='Chennai')&(df['Sales']>40000))]
#answer
#df.loc function filters the rows which satisfy both the conditions only.
#it filters the rows which satisfies both the conditions only.
#negation means not symbol

Retail_shops     City  Sales
0         Croma  Chennai  60000
12      Walmart  Chennai  55000

In [18]:
df[~((df['City']=='Chennai')&(df['Sales']>40000))]

Retail_shops      City  Sales
1   Reliance_mart     Kovai  50000
2            RMKV  Tirupati  70000
3   Chennai_silks       Hyd  55000
4      Big_basket  Tirupati  40000
5         Walmart   Chennai  30000
6   Reliance_mart       Hyd  55000
7            RMKV       Hyd  40000
8   Chennai_silks     Kovai  30000
9      Big_basket      Agra  70000
10        Walmart      Pune  40000
11     Big_basket      Agra  50000

Retail_shops      City  Sales
0           Croma   Chennai  60000
1   Reliance_mart     Kovai  50000
2            RMKV  Tirupati  70000
3   Chennai_silks       Hyd  55000
4      Big_basket  Tirupati  40000
5         Walmart   Chennai  30000
6   Reliance_mart       Hyd  55000
7            RMKV       Hyd  40000
8   Chennai_silks     Kovai  30000
9      Big_basket      Agra  70000
10        Walmart      Pune  40000
11     Big_basket      Agra  50000
12        Walmart   Chennai  55000

In [21]:
df[~((df['City']=='Chennai')|(df['Sales']>40000))]
#in croma and walmart sales are more than 40k.

Retail_shops      City  Sales
4      Big_basket  Tirupati  40000
7            RMKV       Hyd  40000
8   Chennai_silks     Kovai  30000
10        Walmart      Pune  40000

In [23]:
#df[~((df['City']=='Chennai')&(df['Sales']>40000))]
#all records except chennai greater than 40k will be displayed

In [ ]:
#df[(df['City']=='Chennai')|(df['Sales']>40000)]

In [ ]:
#

In [ ]:
#aggregate function:sum,min,mode,count,rank,max,mean,min,

In [35]:
a=df[(df['City']=='Chennai') & (df['Sales']>40000)]
print(type(a.Retail_shops))
print(a.Retail_shops)
#In df,where city is chennai and where sales > than 40000,these records are selected

<class 'pandas.core.series.Series'>
0       Croma
12    Walmart
Name: Retail_shops, dtype: object


In [34]:
a.Retail_shops[12]

'Walmart'

In [ ]:
2)Display the Shop names in above case.


In [28]:
# df[(df['City']=='Chennai') & (df['Sales']>40000)]['Retail_shops'][0][3:][-2:-1]

'm'

In [14]:
df[(df['City']=='Chennai') & (df['Sales']>40000)].Retail_shops


0       Croma
12    Walmart
Name: Retail_shops, dtype: object

In [29]:
df

Retail_shops      City  Sales
0           Croma   Chennai  60000
1   Reliance_mart     Kovai  50000
2            RMKV  Tirupati  70000
3   Chennai_silks       Hyd  55000
4      Big_basket  Tirupati  40000
5         Walmart   Chennai  30000
6   Reliance_mart       Hyd  55000
7            RMKV       Hyd  40000
8   Chennai_silks     Kovai  30000
9      Big_basket      Agra  70000
10        Walmart      Pune  40000
11     Big_basket      Agra  50000
12        Walmart   Chennai  55000

In [22]:
df1=df[(df['City']=='Chennai') & (df['Sales']>40000)]
print(df1)


   Retail_shops     City  Sales
0         Croma  Chennai  60000
12      Walmart  Chennai  55000


In [25]:
print(df1.Sales.unique())
#unique fun gives unique values in the retail shops column

[60000 55000]


In [26]:
print(df1.Retail_shops.nunique())
#number of unique values in retail shops

2


In [28]:
print(df1.City.value_counts())

Chennai    2
Name: City, dtype: int64


In [27]:
print(df.Retail_shops.unique())

['Croma' 'Reliance_mart' 'RMKV' 'Chennai_silks' 'Big_basket' 'Walmart']


In [29]:
df['City'].replace(to_replace={'Kovai':'Coimbatore'},inplace=True)

In [36]:
df.loc[((df['City']=='Coimbatore')&(df['Sales']==250000)),['Sales']]

Sales
1  250000

In [31]:
df.loc[((df['City']=='Coimbatore')&(df['Sales']==50000)),['Sales']]=50000*5

In [33]:
df

Retail_shops        City   Sales
0           Croma     Chennai   60000
1   Reliance_mart  Coimbatore  250000
2            RMKV    Tirupati   70000
3   Chennai_silks         Hyd   55000
4      Big_basket    Tirupati   40000
5         Walmart     Chennai   30000
6   Reliance_mart         Hyd   55000
7            RMKV         Hyd   40000
8   Chennai_silks  Coimbatore   30000
9      Big_basket        Agra   70000
10        Walmart        Pune   40000
11     Big_basket        Agra   50000
12        Walmart     Chennai   55000

In [47]:
df1.Retail_shops.value_counts()
#value conts fun displays count of each and
#every cate level in a categorical column.

Walmart    1
Croma      1
Name: Retail_shops, dtype: int64

In [20]:
df1.Retail_shops.count()

2

In [29]:
#df.City#displays the column values

In [ ]:
#validation,check,matching,where condn(important)
# It is used to retreive  data from df

In [4]:
df

Retail_shops      City  Sales
0           Croma   Chennai  60000
1   Reliance_mart     Kovai  50000
2            RMKV  Tirupati  70000
3   Chennai_silks       Hyd  55000
4      Big_basket  Tirupati  40000
5         Walmart   Chennai  30000
6   Reliance_mart       Hyd  55000
7            RMKV       Hyd  40000
8   Chennai_silks     Kovai  30000
9      Big_basket      Agra  70000
10        Walmart      Pune  40000
11     Big_basket      Agra  50000
12        Walmart   Chennai  55000

In [ ]:
3)Write a program to select shops located in Tamil Nadu.

In [ ]:
4)Replace 'Kovai' with 'Coimbatore' in the original dataframe.
#map function,str.replace function,df.replace function,
#df.loc function,df.iloc function


In [38]:
df

Retail_shops      City  Sales
0           Croma   Chennai  60000
1   Reliance_mart     Kovai  50000
2            RMKV  Tirupati  70000
3   Chennai_silks       Hyd  55000
4      Big_basket  Tirupati  40000
5         Walmart   Chennai  30000
6   Reliance_mart       Hyd  55000
7            RMKV       Hyd  40000
8   Chennai_silks     Kovai  30000
9      Big_basket      Agra  70000
10        Walmart      Pune  40000
11     Big_basket      Agra  50000
12        Walmart   Chennai  55000

In [22]:
df.loc[((df.City=='Tirupati') | (df.City=='Hyd')),:]

Retail_shops     City  Sales
0           Croma  Chennai  60000
1   Reliance_mart    Kovai  50000
5         Walmart  Chennai  30000
8   Chennai_silks    Kovai  30000
12        Walmart  Chennai  55000

In [20]:
df.loc[((df.City=='Kovai') | (df.City=='Chennai'))]

Retail_shops     City  Sales
0           Croma  Chennai  60000
1   Reliance_mart    Kovai  50000
5         Walmart  Chennai  30000
8   Chennai_silks    Kovai  30000
12        Walmart  Chennai  55000

In [ ]:
#df.loc[((df.City=='Kovai') & (df.City=='Chennai')),:]
#both the condn cannot be satisfied at a time as they are applied on the
#same column.
##df.loc[((df.City=='Kovai') & (df.City=='Chennai')),:] same as
##df.loc[((df.City=='Kovai') & (df.City=='Chennai'))]

In [50]:
df[df['City'].isin(['Chennai','Kovai','Hyd'])]['City'].count()
#isin()-isin fun filters multiple values in a column
#Selects records where city isin Chennai and Kovai.

8

In [51]:
df[df['City'].isin(['Tirupati','Hyd'])]#,select the reocords where city is in triupati,hyd
#where condn checks one value in column
#Where condn checks multiple values ina column using isin()


Retail_shops      City  Sales
2           RMKV  Tirupati  70000
3  Chennai_silks       Hyd  55000
4     Big_basket  Tirupati  40000
6  Reliance_mart       Hyd  55000
7           RMKV       Hyd  40000

In [ ]:
df[where condn]

In [ ]:
#where condn is sql is used to retrieve data from table.same concept in df too.


In [25]:
df

Retail_shops      City  Sales
0           Croma   Chennai  60000
1   Reliance_mart     Kovai  50000
2            RMKV  Tirupati  70000
3   Chennai_silks       Hyd  55000
4      Big_basket  Tirupati  40000
5         Walmart   Chennai  30000
6   Reliance_mart       Hyd  55000
7            RMKV       Hyd  40000
8   Chennai_silks     Kovai  30000
9      Big_basket      Agra  70000
10        Walmart      Pune  40000
11     Big_basket      Agra  50000
12        Walmart   Chennai  55000

In [ ]:
#when there are 2 small conditions in main cond,each small condition displays an entire record/row.

In [5]:
#4)select the records of retail shops with sales between 35k to 45 k





df[(df['Sales']>=35000)&(df['Sales']<45000)]
#selects records where sales >35k and sales <45,<=
#and -&
#or-|
#~ selects records which donot satisfy the condn.


Retail_shops      City  Sales
4    Big_basket  Tirupati  40000
7          RMKV       Hyd  40000
10      Walmart      Pune  40000

In [11]:
#Rename Retail_shops to Shops in the above df.
#Display the shop details where maximum sales took place in agra.

In [21]:
df.head(2)

Retail_shops     City  Sales
0          Croma  Chennai  60000
1  Reliance_mart    Kovai  50000

In [22]:
#df.rename(columns={'Shops':"Retail_shops"},inplace=True)

In [23]:
#df[(df['Sales']>=35000)|(df['Sales']<=45000)]

In [24]:
#df['Name']=df['Name'].map({'Jay':'j',"Raju":"r","Ishan":'i',"Nithya":"n"})

#df['Name']=df['name'].replace(to_replace={'old value':'new vaalue','old value2':'new value2'})

In [33]:
df.rename({'Name':'Name_st','Marks':'Marks_st'},inplace=True)

In [38]:
df

Retail_shops      City  Sales
0           Croma   Chennai  60000
1   Reliance_mart     Kovai  50000
2            RMKV  Tirupati  70000
3   Chennai_silks       Hyd  55000
4      Big_basket  Tirupati  40000
5         Walmart   Chennai  30000
6   Reliance_mart       Hyd  55000
7            RMKV       Hyd  40000
8   Chennai_silks     Kovai  30000
9      Big_basket      Agra  70000
10        Walmart      Pune  40000
11     Big_basket      Agra  50000
12        Walmart   Chennai  55000

In [ ]:
#intercept is a point on the y axis where a line/curve intersects it.
#y is dep,t.v,op var.
#x is indep var

In [ ]:
#Create a list.Filter the palindromes in the list.Python program should be in one line 
#only.

In [1]:
mystr='markram'
if mystr==mystr[::-1]:
    print("palindrome")
else:
    print("not palindrome")
    
#madam,markram,dad,malayalam,amma are examples of palindromes.


palindrome


In [1]:
mystr='151'
if mystr==mystr[::-1]:
    print("palindrome")
else:
    print("not palindrome")


palindrome


In [12]:
mylist=['151','123','markram',"dadd","dad"]
list(filter(lambda x:x==x[::-1],mylist))


['151', 'markram', 'dad']

In [8]:
m='123'
m[::-1]

'321'

In [ ]:
#Task:Convert time in hours to minutes

In [1]:
import pandas as pd

In [2]:
import random

In [2]:
dict_a={'time':['1hrs 30mins','2hrs 45mins','3hrs 15mins']}

In [14]:
dict_a    

{'time': ['1hrs 30mins', '2hrs 45mins', '3hrs 15mins']}

In [ ]:
#convert dict to pandas dataframe

In [3]:
df1=pd.DataFrame(dict_a)

In [5]:
df1

time
0  1hrs 30mins
1  2hrs 45mins
2  3hrs 15mins

In [ ]:
#step2:try 4 codesstr.replace(),str.slice(),pd.to_datetime(),apply and lambda function,
#two techiques to use apply and lambdafunction.
#use x.hour and x.minute attributes codes
#use split function then x[0] is hour value and x[1] is minute value

In [ ]:
#step2 : replace hr with : and mins with space value using str.replace function
#step 3:convert time in object to datetime format.
#you can use apply and lambda function on datetime values only.
#i can use x.hour attribute ,x.minute attribute in datetime values only not on object column

In [6]:
df1.time=df1.time.str.replace('hrs ',':').str.replace('mins','')
#'' is not space
#' ' is space
#replaced mins with empty.thats it.

In [7]:
df1

time
0  1:30
1  2:45
2  3:15

In [23]:
df1.dtypes

time    object
dtype: object

In [8]:
df1['time']=pd.to_datetime(arg=df1['time'],utc=True)

In [28]:
df1.dtypes

time    datetime64[ns, UTC]
dtype: object

In [9]:
df1

time
0 2024-05-29 01:30:00+00:00
1 2024-05-29 02:45:00+00:00
2 2024-05-29 03:15:00+00:00

In [10]:
df1['time']=df1['time'].apply(lambda x:x.hour*60+x.minute)

In [ ]:
1st iter,x=2024-05-29 01:30:00+00:00
x.hour=1
x.minute=30

In [ ]:
90

In [ ]:
2nd iter,x=2024-05-29 02:45:00+00:00
x.hour=2
x.minute=45  

In [12]:
df1

time
0    90
1   165
2   195

In [ ]:
#\ is for new line
#if i do not put \ i have to put or cond in above line.code will be lengthy.